//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GruppG.Models.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class FavoriteChannel
    {
        public int Id { get; set; }
        public Nullable<int> Person { get; set; }
        public Nullable<int> Chanel { get; set; }
    
        public virtual Chanel Chanel1 { get; set; }
    }
}
